point docs to core docs site
snowplow/dbt-snowplow-mobile pull request #48
Opened 2022-10-11 13:03 UTC by rlh1994

## Description & motivation
Docs moved to https://docs.snowplow.io/docs/modeling-your-data/modeling-your-data-with-dbt/

## Checklist
- [x] I have verified that these changes work locally
- [x] I have updated the README.md (if applicable)
- [x] I have added tests & descriptions to my models (and macros if applicable)

2022-10-11 13:03 UTC, snowplowcla commented
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

2022-10-14 18:44 UTC, paulboocock requested changes

2022-10-14 18:44 UTC, paulboocock commented on docs/markdown/snowplow_mobile_overview.md
> +**For more information, including a QuickStart guide, operation and configuration, and implementing your own custom modules on top of this please visit the [Snowplow Docs](https://docs.snowplowanalyt
```suggestion
**For more information, including a QuickStart guide, operation and configuration, and implementing your own custom modules on top of this please visit the [Snowplow Docs](https://docs.snowplow.io/docs/modeling-your-data/modeling-your-data-with-dbt/).**
```

2022-10-14 21:30 UTC, rlh1994 commented on docs/markdown/snowplow_mobile_overview.md
> +**For more information, including a QuickStart guide, operation and configuration, and implementing your own custom modules on top of this please visit the [Snowplow Docs](https://docs.snowplowanalyt
Replaced all instances to snowplow.io

2022-10-18 12:45 UTC, paulboocock commented
Looks good, but would be good to figure out whats going on with the tests. Perhaps the same issue as with the `web` package PR?

2022-10-18 13:01 UTC, emielver commented
> Looks good, but would be good to figure out whats going on with the tests. Perhaps the same issue as with the `web` package PR?

@paulboocock it seems to be a bug in dbt v1.3.0, trying to get together enough info for a bug report on their repo but will likely take a bit to sort out since they're in full Coalesce mode atm. We're hardcoding dbt v1.2.x in the tests now and that's passing fine

2022-10-18 13:11 UTC, merged